import React from "react";

export default function AssessTailwind({ userSolution }) {
  let tailwindKeywords = {
    accentColor: "",
    accessibility: "",
    alignContent: "",
    alignItems: "",
    alignSelf: "",
    animation: "",
    appearance: "",
    aspectRatio: "",
    backdropBlur: "",
    backdropBrightness: "",
    backdropContrast: "",
    backdropFilter: "",
    backdropGrayscale: "",
    backdropHueRotate: "",
    backdropInvert: "",
    backdropOpacity: "",
    backdropSaturate: "",
    backdropSepia: "",
    backgroundAttachment: "",
    backgroundBlendMode: "",
    backgroundClip: "",
    backgroundColor: "",
    backgroundImage: "",
    backgroundOpacity: "",
    backgroundOrigin: "",
    backgroundPosition: "",
    backgroundRepeat: "",
    backgroundSize: "",
    blur: "",
    borderCollapse: "",
    borderColor: "",
    borderOpacity: "",
    borderRadius: "",
    borderSpacing: "",
    borderStyle: "",
    borderWidth: "",
    boxDecorationBreak: "",
    boxShadow: "",
    boxShadowColor: "",
    boxSizing: "",
    breakAfter: "",
    breakBefore: "",
    breakInside: "",
    brightness: "",
    captionSide: "",
    caretColor: "",
    clear: "",
    columns: "",
    contain: "",
    container: "",
    content: "",
    contrast: "",
    cursor: "",
    display: "",
    divideColor: "",
    divideOpacity: "",
    divideStyle: "",
    divideWidth: "",
    dropShadow: "",
    fill: "",
    filter: "",
    flex: "flex",
    flexBasis: "",
    flexDirection: "",
    flexGrow: "",
    flexShrink: "",
    flexWrap: "",
    float: "",
    fontFamily: "font-",
    fontSize: "text-Regex",
    fontSmoothing: "",
    fontStyle: "",
    fontVariantNumeric: "",
    fontWeight: "text-Regex",
    forcedColorAdjust: "",
    gap: "gap-",
    gradientColorStops: "",
    grayscale: "",
    gridAutoColumns: "",
    gridAutoFlow: "",
    gridAutoRows: "",
    gridColumn: "",
    gridColumnEnd: "",
    gridColumnStart: "",
    gridRow: "",
    gridRowEnd: "",
    gridRowStart: "",
    gridTemplateColumns: "",
    gridTemplateRows: "",
    height: "",
    hueRotate: "",
    hyphens: "",
    inset: "",
    invert: "",
    isolation: "",
    justifyContent: "",
    justifyItems: "",
    justifySelf: "",
    letterSpacing: "",
    lineClamp: "",
    lineHeight: "",
    listStyleImage: "",
    listStylePosition: "",
    listStyleType: "",
    margin: "",
    maxHeight: "",
    maxWidth: "max-w-",
    minHeight: "min-h-",
    minWidth: "min-w-",
    mixBlendMode: "",
    objectFit: "",
    objectPosition: "",
    opacity: "",
    order: "",
    outlineColor: "",
    outlineOffset: "",
    outlineStyle: "",
    outlineWidth: "",
    overflow: "",
    overscrollBehavior: "",
    padding: "",
    placeContent: "",
    placeItems: "",
    placeSelf: "",
    placeholderColor: "",
    placeholderOpacity: "",
    pointerEvents: "",
    position: "",
    preflight: "",
    resize: "",
    ringColor: "",
    ringOffsetColor: "",
    ringOffsetWidth: "",
    ringOpacity: "",
    ringWidth: "",
    rotate: "",
    saturate: "",
    scale: "",
    scrollBehavior: "",
    scrollMargin: "",
    scrollPadding: "",
    scrollSnapAlign: "",
    scrollSnapStop: "",
    scrollSnapType: "",
    sepia: "",
    size: "",
    skew: "",
    space: "",
    stroke: "",
    strokeWidth: "",
    tableLayout: "",
    textAlign: "",
    textColor: "",
    textDecoration: "",
    textDecorationColor: "",
    textDecorationStyle: "",
    textDecorationThickness: "",
    textIndent: "",
    textOpacity: "",
    textOverflow: "",
    textTransform: "",
    textUnderlineOffset: "",
    textWrap: "",
    touchAction: "",
    transform: "",
    transformOrigin: "",
    transitionDelay: "",
    transitionDuration: "",
    transitionProperty: "",
    transitionTimingFunction: "",
    translate: "",
    userSelect: "",
    verticalAlign: "",
    visibility: "",
    whitespace: "",
    width: "w-",
    willChange: "",
    wordBreak: "",
    zIndex: "z-",
  };

  let included;

  // if (userSolution.includes(tailwindKeywords.maxWidth)) {
  //   included = "max-width is included";
  // }

  // for...in allows you to iterate over js objects
  for (let key in tailwindKeywords) {
    if (userSolution.includes(tailwindKeywords[key])) {
      included = key + " is included";
    }
  }

  return (
    <>
      <p className="text-2xl text-white">{included}</p>
    </>
  );
}
